### PR TITLE
More renames to .md for better rendering

### PR DESCRIPTION
**Pull request by adrianreber**
And some trailing whitespaces removed

### CODE REVIEW

**Review by axkg — CHANGES_REQUESTED** [review]
Sorry for being annoying, but without the corresponding change in the automake Makefile we drop these files from the _dist_ tarball - the "standard" filenames without .md extension were picked up by automake automagically.
```
diff --git a/Makefile.am b/Makefile.am
index 2468d9c..4720897 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -3,6 +3,9 @@ SUBDIRS = src icons help
 EXTRA_DIST = COPYING-DOCS\
        README.md\
        INSTALL.md\
+       THANKS.md\
+       TODO.md\
+       AUTHORS.md\
        README.PERFORMANCE.md\
        terminatorX.spec.in\
        terminatorX.appdata.xml\

**Comment by adrianreber** [comment]
This time I actually grepped for the file name to avoid errors like in the previous PR :wink: 

I was not aware that these files are added automatically. Will fix the PR.

**Comment by adrianreber** [comment]
Sounds like adding a `make dist` to CI would have caught errors like this.

**Comment by axkg** [comment]
> Sounds like adding a `make dist` to CI would have caught errors like this.

Unfortunately not, the files are just be missing from the tarball - `make dist` still completes without error.

**Comment by adrianreber** [comment]
PR has been updated.

**Review by axkg — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
